"""empty message

Revision ID: 0a299d947aa9
Revises: 211510dd76e9
Create Date: 2020-06-18 16:46:06.829222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a299d947aa9'
down_revision = '211510dd76e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avg_price_target_capture', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('avg_price_target_capture_percentile', sa.Float(), nullable=True))
    op.drop_column('users', 'brier_score_percentile')
    op.drop_column('users', 'brier_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('brier_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('brier_score_percentile', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'avg_price_target_capture_percentile')
    op.drop_column('users', 'avg_price_target_capture')
    # ### end Alembic commands ###
