"""empty message

Revision ID: 211510dd76e9
Revises: 
Create Date: 2020-06-17 08:27:36.689365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '211510dd76e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ideas', 'bull_probability')
    op.drop_column('ideas', 'bull_target')
    op.drop_column('ideas', 'base_probability')
    op.drop_column('ideas', 'base_target')
    op.drop_column('ideas', 'bear_probability')
    op.drop_column('ideas', 'bear_target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('bear_target', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ideas', sa.Column('bear_probability', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ideas', sa.Column('base_target', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ideas', sa.Column('base_probability', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ideas', sa.Column('bull_target', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ideas', sa.Column('bull_probability', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
